default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_40568_development

test:
  <<: *default
  database: protospace_40568_test

production:
  <<: *default
  database: protospace_40568_production
  username: protospace_40568
  password: <%= ENV["PROTOSPACE_40568_DATABASE_PASSWORD"] %>
